### ISSUE TITLE
Don't use hardcoded <rootDir>/build as temp path when saving

### ISSUE THREAD

**Issue by matthiesenj** [prb28/vscode-amiga-assembly#107]
It's debatable whether the build output path should be hardcoded to the above, but I think at least the .o vasm output file generated when saving (for highlighting errors, etc) should use the system or user temp directory path for this.

The reason behind this is, I tried to build using a makefile using "build" as the path for any intermediate files, and realized I got a .o file there when saving. This .o file is not needed for anything else (and may use different vasm options), so it really shouldn't end up in the workspace (even if I could use a different path in the makefile).

**Comment by prb28** [comment]
I think the build dir has all is place in the workspace folder (and yes it's debatable). Now I agree that the .o files for syntax checking could be in a temp dir. But I don't like temp dirs because it's system dependent (I build for os, linux and windows) and it ends with a root disk full of crap if it's badly managed (I have to look if vscode has something to manage it).
So I think the better way to handle this is to have a setting to choose the build dir and the syntax temporary dir (that can be set to a system temp dir).
Would it answer your request ?

**Comment by matthiesenj** [comment]
I wasn't criticizing having the build dir in the workspace, what I meant was that it was debatable whether it was a good idea that it's hardcoded to 'build' :-)

Having the path for the temp syntax-checking .o files configurable sounds perfectly fine, as long as it'll work with env vars. That way the user can set it to e.g. '%TEMP%' on Windows, '$TEMP' on linux, etc.

**Comment by prb28** [comment]
A first implementation will come in 0.19, env vars support will come later with #109 .

**Comment by matthiesenj** [comment]
I tried changing `amiga-assembly.tmpDir` to an absolute path, and it seems the extension skips the syntax check run of vasm without any error messages in this case - I suppose this is a bug??

If I use a non-existent path (absolute or relative), vscode shows a popup error in the corner.

**Comment by prb28** [comment]
Sorry for that, yes it looks like a bug.
