### ISSUE TITLE
The built in emulator runs slow

### ISSUE THREAD

**Issue by C64HexCoder** [prb28/vscode-amiga-assembly#220]
I coded an intro and it runs very slow on the built in emulator and does not run coreectly on other emulators.

Whay is that and how do i cange the build in emulator settings?

**Comment by prb28** [comment]
Un debug mode the emulator run slower and that's normal, je has to do some more checks while running.
I assume you are on Linux or OS X because it's an old version of fsuae and it may behave differently from a more recent version.
You can change some launch's parameters of the emulator in the launch.json file. In particular change the kickstart, the old default aros rom will not be the best in your case.
