### ISSUE TITLE
Error debugging a binary that is not compiled in the workbench

### ISSUE THREAD

**Issue by cvalcke** [prb28/vscode-amiga-assembly#50]
I'm trying to debug a binary that I compiled myself (I think I added the debug flags) but I think it cannot find the original source file (amiforce.s in my case)

Is there a path I forgot to configure?

Regs,

![selection_665](https://user-images.githubusercontent.com/354495/52001373-89c12200-24bf-11e9-935b-730b242408b6.png)

**Comment by prb28** [comment]
The debugger is looking for "amiforce.s", so there must be some debug info in the program.
(You can check it by dumping the file in hex, the debug info is in ascii)

Now the debugger does not find the file, it uses path replacements when the sources were build in the workspace, otherwise, you can try to set the replacement paths in the "sourceFileMap" attribute of the launch.json file.

```
    "configurations": [
        {
            "type": "fs-uae",
...
            "sourceFileMap": {
                "": "my/parent/path/"
            }
...
        },
]
```

Hope this helps.

**Comment by cvalcke** [comment]
It works nice with the sourceFileMap attribute.

Merci beaucoup !!

**Comment by prb28** [comment]
de rien ;-)

I've added some documentation about the settings in the wiki, it was missing...
