### ISSUE TITLE
Format ASM files with tabs

### ISSUE THREAD

**Issue by prb28** [prb28/vscode-amiga-assembly#73]
Optionally select tabs instead of spaces for asm source format.

**Comment by jonathanbennett73** [comment]
I was just going to add this to the issue log but this popped up as a duplicate so you must have seen in on EAB :)

**Comment by jonathanbennett73** [comment]
You asked for an example on EAB. Personally from my Devpac/Asmone habits my source looks like:
`.makecl:
	swap	d1			;Swap high & low words
	move.w	d1,2(a0)		;High ptr
	swap	d1			;Swap high & low words
	move.w	d1,6(a0)		;Low ptr
	addq.l	#8,a0			;Next set of ptrs
	add.l	d2,d1			;Next bitplane
	dbf	d0,.makecl`

So tab size on that old IDE was always 8. I'd do a label then tab (if no space I'd go on the next line) so 1 tab to column 9 for the instruction. Then tab (col 17) for opcode. Then tab to column 41 (or later if no room) for comments.

Maybe I could try and go to spaces now that I've moved my assembling completely into Windows. I uses spaces in C# because everyone else does...

**Comment by prb28** [comment]
Yes, spaces are more cross-platform / cross-editor friendly ;-).
But that's an habit (ivory tower) of every developer so I understand.
Thanks for the example, that helps!
